Import('aligners_env')

penv = aligners_env.Clone()
penv['CFLAGS'] += ' -D_XOPEN_SOURCE=600 -g'

# TODO: Remove fastq_batch_reader_omp so Glob can be used
aligners_env['objects'] += penv.Object(Split('macros.c sse.c smith_waterman.c'))
