import os

Import('containersenv')

containers_path = os.getcwd() + '/../'

containerstest = containersenv.Clone()
containerstest['CPPPATH'] += [containers_path]
containerstest['LIBS'] += ['check', 'm', 'rt']


check_linked_list = containerstest.Program('linked_list.test', 
                    	         	   source = ['linked_list_test.c', 
				           	     '%s/linked_list.o' % containers_path
                                          	    ])
