Import('aligners_env', 'compiler', 'debug')

search_env = aligners_env.Clone()
search_env['objects'] = []

search_env['CFLAGS'] += ' -m64 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -fPIC -DFM_COMP_64' #-msse4.2 -DCSALIB_SEARCH -DVERBOSE_DBG

aligners_env['objects'] += search_env.Object(Glob('*.c'))
