Import('debug', 'compiler')

# Initialize environment
env = Environment(CC = compiler,
                  CFLAGS = '-std=c99 -D_GNU_SOURCE -D_XOPEN_SOURCE=600 ',
                  CPPPATH = ['#', '/usr/include/libxml2', '.' ],
                  LIBPATH = ['/usr/lib' ])

env.Decider('MD5-timestamp')

if debug == 1:
    env['CFLAGS'] += '-O0 -g -fdump-rtl-expand'
else:
    env['CFLAGS'] += '-O3 -g'



# Targets
commons_obj = env.Object(Glob('commons/*.c'))
containers_obj = env.Object(Glob('containers/*.c'))


# Compile containers/cprops objects but ONLY those used for our libraries
cpropsenv = Environment(CC = compiler,
                        CFLAGS = '-D_REENTRANT -D_GNU_SOURCE -DHAVE_CONFIG_H ',
                        CPPPATH = ['#', '/usr/include/libxml2', '.' ],
                        LIBPATH = ['/usr/lib' ])

cpropsenv.Decider('MD5-timestamp')

if debug == 1:
    cpropsenv['CFLAGS'] += '-O0 -g -fdump-rtl-expand'
else:
    cpropsenv['CFLAGS'] += '-O3'
cprops_obj = cpropsenv.Object(['containers/cprops/avl.c', 'containers/cprops/collection.c', 'containers/cprops/hashlist.c', 'containers/cprops/hashtable.c', 'containers/cprops/heap.c', 'containers/cprops/linked_list.c', 'containers/cprops/log.c', 'containers/cprops/mempool.c', 'containers/cprops/rb.c', 'containers/cprops/util.c', 'containers/cprops/vector.c', 'containers/cprops/trie.c', 'containers/cprops/mtab.c'])

# Compile commons/sqlite objects
sqliteenv = Environment(CC = compiler,
                        CFLAGS = '-DHAVE_CONFIG_H -fPIC -DPIC ',
                        CPPPATH = ['#', '.' ],
                        LIBPATH = ['/usr/lib' ])

sqliteenv.Decider('MD5-timestamp')

if debug == 1:
    sqliteenv['CFLAGS'] += '-O0 -g -fdump-rtl-expand'
else:
    sqliteenv['CFLAGS'] += '-O2 -g'
sqlite_obj = sqliteenv.Object(Glob('commons/sqlite/*.c'))


# Compile commons/argtable objects
argtableenv = Environment(CC = compiler,
                        CFLAGS = '-DHAVE_CONFIG_H -fPIC -DPIC ',
                        CPPPATH = ['#', '.' ],
                        LIBPATH = ['/usr/lib' ])

argtableenv.Decider('MD5-timestamp')

if debug == 1:
    argtableenv['CFLAGS'] += '-O0 -g -fdump-rtl-expand'
else:
    argtableenv['CFLAGS'] += '-O2 -g'
argtable_obj = argtableenv.Object(Glob('commons/argtable/*.c'))


# Compile commons/config objects
configenv = Environment(CC = compiler,
                        CFLAGS = '-DHAVE_CONFIG_H -D_REENTRANT -Wall -Wshadow -Wextra -Wdeclaration-after-statement -Wno-unused-parameter ',
                        CPPPATH = ['#', '.' ],
                        LIBPATH = ['/usr/lib' ])

configenv.Decider('MD5-timestamp')

if debug == 1:
    configenv['CFLAGS'] += '-O0 -g -fdump-rtl-expand'
else:
    configenv['CFLAGS'] += '-O2 -g'
config_obj = configenv.Object(Glob('commons/config/*.c'))

# Objects
env.Library('common', commons_obj + containers_obj + cprops_obj + sqlite_obj + argtable_obj + config_obj)

# Run tests
containers_test = SConscript("containers/test/SConscript", exports = ['env', 'debug'] )